//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attend
    {
        public int ID { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<int> eventid { get; set; }
        public string DayNUM { get; set; }
        public Nullable<bool> DayAttend { get; set; }
        public Nullable<bool> Present { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> From_Time { get; set; }
        public Nullable<System.TimeSpan> To_Time { get; set; }
        public string agenda { get; set; }
        public string non1 { get; set; }
        public Nullable<int> non2 { get; set; }
        public Nullable<System.DateTime> non3 { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual requests1 requests1 { get; set; }
    }
}
