//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        public BRANCH()
        {
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
        }
    
        public string BRANCH_ID { get; set; }
        public string BRANCH1 { get; set; }
        public string BRANCH_MANAGER { get; set; }
        public string BRANCH_DESC { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }
    }
}
