//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int CatID { get; set; }
        public string CatName { get; set; }
        public string CatDescription { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
    }
}
