//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_type
    {
        public contract_type()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int contractTypeid { get; set; }
        public string contract_Type_code { get; set; }
        public string contract_type_name { get; set; }
        public string contract_type_description { get; set; }
        public Nullable<int> stafid { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
        public virtual staff staff { get; set; }
    }
}
