//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_details
    {
        public contract_details()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int contractdetailsid { get; set; }
        public string contract_details_id { get; set; }
        public string contract_details_description_english { get; set; }
        public string contract_details_abreviation_english { get; set; }
        public string contract_details_description_french { get; set; }
        public string contract_details_abreviation_french { get; set; }
        public string contract_details_status { get; set; }
        public string contract_details_created_by { get; set; }
        public Nullable<System.DateTime> contract_details_created_datetime { get; set; }
        public string contract_details_last_modified_by { get; set; }
        public Nullable<System.DateTime> contract_details_last_modified_datetime { get; set; }
        public string contract_details_deleted_by { get; set; }
        public Nullable<System.DateTime> contract_details_deleted_datetime { get; set; }
        public string contract_type_code { get; set; }
        public Nullable<int> fundid { get; set; }
        public Nullable<int> staffid { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual staff staff { get; set; }
    }
}
