//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.Country_office = new HashSet<Country_office>();
            this.staffs = new HashSet<staff>();
            this.governorates = new HashSet<governorate>();
            this.districts = new HashSet<district>();
            this.MissionItineraries = new HashSet<MissionItinerary>();
            this.MissionItineraries1 = new HashSet<MissionItinerary>();
            this.MissionAuthorizations = new HashSet<MissionAuthorization>();
        }
    
        public int countryid { get; set; }
        public string country_name { get; set; }
        public string country_description { get; set; }
    
        public virtual ICollection<Country_office> Country_office { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<governorate> governorates { get; set; }
        public virtual ICollection<district> districts { get; set; }
        public virtual ICollection<MissionItinerary> MissionItineraries { get; set; }
        public virtual ICollection<MissionItinerary> MissionItineraries1 { get; set; }
        public virtual ICollection<MissionAuthorization> MissionAuthorizations { get; set; }
    }
}
