//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTypt
    {
        public CourseTypt()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int CourseTypeID { get; set; }
        public string CourseType { get; set; }
        public string Comment { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
