//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseRegs = new HashSet<CourseReg>();
            this.CourseSessions = new HashSet<CourseSession>();
            this.CourseDetails = new HashSet<CourseDetail>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> CourseTypeID { get; set; }
        public string CourseDescp1 { get; set; }
        public string CourseDescp2 { get; set; }
        public string CourseDescp3 { get; set; }
    
        public virtual ICollection<CourseReg> CourseRegs { get; set; }
        public virtual ICollection<CourseSession> CourseSessions { get; set; }
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
        public virtual CourseTypt CourseTypt { get; set; }
        public virtual unit unit { get; set; }
    }
}
