//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
        }
    
        public string DEP_ID { get; set; }
        public string DEP_NAME { get; set; }
        public string PARENT_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string DEP_MANAGER { get; set; }
        public string DEP_DESC { get; set; }
        public Nullable<int> MaxEmpNo { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }
    }
}
