//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.staffs = new HashSet<staff>();
            this.staffs1 = new HashSet<staff>();
            this.WardenGroups = new HashSet<WardenGroup>();
        }
    
        public int areacode { get; set; }
        public string area_name { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> governorates_code { get; set; }
    
        public virtual country country { get; set; }
        public virtual governorate governorate { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<staff> staffs1 { get; set; }
        public virtual ICollection<WardenGroup> WardenGroups { get; set; }
    }
}
