//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.VAC_TRANS = new HashSet<VAC_TRANS>();
        }
    
        public string EMP_ID { get; set; }
        public string EMP_FIRST_NAME { get; set; }
        public string EMP_MIDDLE_NAME { get; set; }
        public string EMP_LAST_NAME { get; set; }
        public string PREFIX { get; set; }
        public string NATIONALITY_ID { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string GENDER { get; set; }
        public string PHONE { get; set; }
        public string ADDRESSID { get; set; }
        public string CELL { get; set; }
        public string MARTIAL_STATUS_ID { get; set; }
        public string VACATION_GROUP_ID { get; set; }
        public string PERMISSION_GROUP_ID { get; set; }
        public string HOLIDAY_GROUP_ID { get; set; }
        public string DEPID { get; set; }
        public string JOB_ID { get; set; }
        public string QUAKIFICATION { get; set; }
        public string GRADU_DEPT { get; set; }
        public string GRADU_GRADE { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string BRANCH_ID { get; set; }
        public string NATIONAL_NO { get; set; }
        public string NATIONAL_NO_IP { get; set; }
        public Nullable<System.DateTime> NATIONAL_NO_ID { get; set; }
        public string MILIT_SERV { get; set; }
        public string OTHER1 { get; set; }
        public string OTHER2 { get; set; }
        public string OTHERDATE { get; set; }
        public byte[] PIC { get; set; }
        public Nullable<System.DateTime> RESIGN_DATE { get; set; }
        public Nullable<bool> RESIGNED { get; set; }
        public string RESIGN_REASON { get; set; }
        public string ACCESS_CARD { get; set; }
        public string SAL_GRP_ID { get; set; }
        public string CUR_ID { get; set; }
        public Nullable<bool> EMPLOYEE1 { get; set; }
        public Nullable<int> USER_CARD { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string MANAGER { get; set; }
        public string ZONE_ID { get; set; }
        public string STEP_ID { get; set; }
        public Nullable<int> Emp_Agent_Id { get; set; }
        public Nullable<int> Emp_Insur { get; set; }
        public string Contract_Code { get; set; }
        public Nullable<int> FLEXY_GRPS { get; set; }
        public string CST_CD { get; set; }
        public Nullable<System.DateTime> SSN_DT { get; set; }
        public string RESIGN_REASON_ID { get; set; }
        public string MILIT_SERV_NO { get; set; }
        public Nullable<System.DateTime> MILIT_SERV_ISUDT { get; set; }
        public Nullable<System.DateTime> MILIT_SERV_EXPDT { get; set; }
        public Nullable<System.DateTime> NATIONAL_NO_ED { get; set; }
        public string Portal_UsrNam { get; set; }
        public Nullable<int> Send_Mail { get; set; }
        public string Cont_Type_Id { get; set; }
        public Nullable<System.DateTime> Contract_End { get; set; }
        public Nullable<int> empid { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual staff staff { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual Job_DESCRIPTION Job_DESCRIPTION { get; set; }
        public virtual ICollection<VAC_TRANS> VAC_TRANS { get; set; }
    }
}
