//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class functional_title
    {
        public functional_title()
        {
            this.staffs = new HashSet<staff>();
            this.requests = new HashSet<request>();
        }
    
        public int functionaltitleid { get; set; }
        public string functional_title_id { get; set; }
        public string functional_title_description_english { get; set; }
        public string functional_title_abreviation_english { get; set; }
        public string functional_title_description_french { get; set; }
        public string functional_title_abreviation_french { get; set; }
        public string functional_title_status { get; set; }
        public string functional_title_created_by { get; set; }
        public Nullable<System.DateTime> functional_title_created_datetime { get; set; }
        public string functional_title_last_modified_by { get; set; }
        public Nullable<System.DateTime> functional_title_last_modified_datetime { get; set; }
        public string functional_title_deleted_by { get; set; }
        public Nullable<System.DateTime> functional_title_deleted_datetime { get; set; }
        public Nullable<int> stafid { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
