//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public Fund()
        {
            this.contract_details = new HashSet<contract_details>();
        }
    
        public int fundid { get; set; }
        public string fund_code { get; set; }
        public string resource { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<contract_details> contract_details { get; set; }
    }
}
