//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class governorate
    {
        public governorate()
        {
            this.staffs = new HashSet<staff>();
            this.districts = new HashSet<district>();
        }
    
        public int governorates_code { get; set; }
        public string governorates_name { get; set; }
        public string governorates_description { get; set; }
        public Nullable<int> country_code { get; set; }
        public string staff_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<district> districts { get; set; }
    }
}
