//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_DESCRIPTION
    {
        public Job_DESCRIPTION()
        {
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
        }
    
        public string JOB_ID { get; set; }
        public string JOB_TITLE { get; set; }
        public string SUPERVISOR_TITLE { get; set; }
        public Nullable<double> SALARY_RANGE_F { get; set; }
        public Nullable<double> SALARY_RANGE_T { get; set; }
        public string POSITION_PURPOSE { get; set; }
        public string ESSENTIAL_DUTIES { get; set; }
        public string OTHER_DUTIES { get; set; }
        public string SUPERVISORY_RESP { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }
    }
}
