//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionAuthorizationH
    {
        public int MissionID { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string MissionItinerary { get; set; }
        public string funding { get; set; }
        public Nullable<bool> ClearedBySupervisor { get; set; }
        public string MissionObjective { get; set; }
        public string ExpectedOutputs { get; set; }
        public string Achievements { get; set; }
        public string FollowUp { get; set; }
        public string StaffSignature { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string RDORDRDSignature { get; set; }
        public Nullable<System.DateTime> RDORDRDDate { get; set; }
        public Nullable<bool> canbedone { get; set; }
        public Nullable<bool> delted { get; set; }
        public Nullable<bool> updated { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    }
}
