//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionType
    {
        public MissionType()
        {
            this.MissionAuthorizations = new HashSet<MissionAuthorization>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Non1 { get; set; }
        public Nullable<int> Non2 { get; set; }
        public Nullable<System.DateTime> Non3 { get; set; }
    
        public virtual ICollection<MissionAuthorization> MissionAuthorizations { get; set; }
    }
}
