//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionAuthorization1
    {
        public int MissionID { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string MissionItinerary { get; set; }
        public string funding { get; set; }
        public Nullable<bool> ClearedBySupervisor { get; set; }
        public string MissionObjective { get; set; }
        public string ExpectedOutputs { get; set; }
        public string Achievements { get; set; }
        public string FollowUp { get; set; }
        public string StaffSignature { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string RDORDRDSignature { get; set; }
        public Nullable<System.DateTime> RDORDRDDate { get; set; }
        public Nullable<bool> canbedone { get; set; }
        public Nullable<int> staffonbehalf { get; set; }
        public Nullable<int> nnon1 { get; set; }
        public Nullable<System.DateTime> non2 { get; set; }
        public Nullable<int> non3 { get; set; }
        public string non4 { get; set; }
        public Nullable<int> non5 { get; set; }
        public Nullable<bool> Signature1 { get; set; }
        public Nullable<System.DateTime> Signature1Date { get; set; }
        public Nullable<bool> Signature2 { get; set; }
        public Nullable<System.DateTime> Signature2Date { get; set; }
        public Nullable<bool> Signature3 { get; set; }
        public Nullable<System.DateTime> Signature3Date { get; set; }
        public string clearances { get; set; }
        public Nullable<bool> BSITF { get; set; }
        public Nullable<System.DateTime> Bexpiredate { get; set; }
        public Nullable<bool> ASITF { get; set; }
        public Nullable<System.DateTime> Aexpiredate { get; set; }
        public Nullable<bool> SSAFE { get; set; }
        public Nullable<System.DateTime> Sexpiredate { get; set; }
        public string non6 { get; set; }
        public Nullable<bool> non7 { get; set; }
        public Nullable<System.DateTime> nonn8 { get; set; }
        public Nullable<int> nono9 { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string non10 { get; set; }
        public string non11 { get; set; }
        public Nullable<bool> non12 { get; set; }
        public Nullable<System.DateTime> non13 { get; set; }
        public string non14 { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
