//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MissionAuthorization
    {
        public MissionAuthorization()
        {
            this.MissionItineraries = new HashSet<MissionItinerary>();
        }
    
        public int MissionID { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string MissionItinerary { get; set; }

        //[Required(ErrorMessage = "this field is mandatory")] 

         [Required(ErrorMessage = "this field is mandatory")]
        public string funding { get; set; }

         [Required(ErrorMessage = "this field is mandatory")]
        public Nullable<bool> ClearedBySupervisor { get; set; }

         [Required(ErrorMessage = "this field is mandatory")]
        public string MissionObjective { get; set; }

         [Required(ErrorMessage = "this field is mandatory")]
        public string ExpectedOutputs { get; set; }
        public string Achievements { get; set; }
        public string FollowUp { get; set; }

         [Required(ErrorMessage = "this field is mandatory")] 
        public string StaffSignature { get; set; }

        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string RDORDRDSignature { get; set; }
        public Nullable<System.DateTime> RDORDRDDate { get; set; }

         [Required(ErrorMessage = "this field is mandatory")]
        public Nullable<bool> canbedone { get; set; }
        public Nullable<int> staffonbehalf { get; set; }
        public Nullable<int> nnon1 { get; set; }
        public Nullable<System.DateTime> non2 { get; set; }
        public Nullable<int> non3 { get; set; }
        public string non4 { get; set; }
        public Nullable<int> non5 { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }

          [Required(ErrorMessage = "this field is mandatory")]
        public Nullable<int> Mission_Type { get; set; }

          [Required(ErrorMessage = "this field is mandatory")] 
        public Nullable<bool> UberCareem { get; set; }


        public string other { get; set; }
        public string files { get; set; }
        public Nullable<int> destinationCountry { get; set; }
        public string destinationTwon { get; set; }
        public Nullable<int> non16 { get; set; }
        public string non17 { get; set; }

        [Required(ErrorMessage = "this field is mandatory")]
        public Nullable<bool> non18 { get; set; }
        public Nullable<System.DateTime> non19 { get; set; }

        public virtual staff staff { get; set; }
        public virtual MissionType MissionType { get; set; }
        public virtual ICollection<MissionItinerary> MissionItineraries { get; set; }
        public virtual country country { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
