//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Request
    {
        public int ID { get; set; }
        public string VendorNumber { get; set; }
        public string Descrption { get; set; }
        public string Amount { get; set; }
        public string Requesting_Unit { get; set; }
        public string AssignetTo { get; set; }
    }
}
