//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class securitytracking
    {
        public int secid { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<bool> incountry { get; set; }
        public Nullable<bool> outofcountry { get; set; }
        public Nullable<bool> randrleave { get; set; }
        public Nullable<bool> leave { get; set; }
        public Nullable<bool> onmission { get; set; }
        public string remark { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
