//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sir_item
    {
        public sir_item()
        {
            this.sir_item_category_access = new HashSet<sir_item_category_access>();
            this.sir_staff_item = new HashSet<sir_staff_item>();
        }
    
        public string sir_item_id { get; set; }
        public string sir_item_desc { get; set; }
        public string sir_item_allow_attachment { get; set; }
        public string sir_item_status { get; set; }
        public string created_by { get; set; }
        public string created_datetime { get; set; }
        public string updated_by { get; set; }
        public string updated_datetime { get; set; }
        public string deleted_by { get; set; }
        public string deleted_datetime { get; set; }
    
        public virtual ICollection<sir_item_category_access> sir_item_category_access { get; set; }
        public virtual ICollection<sir_staff_item> sir_staff_item { get; set; }
    }
}
