//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sir_category_access
    {
        public string sir_category_access_id { get; set; }
        public string sir_access_id { get; set; }
        public string sir_category_id { get; set; }
        public string sir_category_access_status { get; set; }
        public string created_by { get; set; }
        public string created_datetime { get; set; }
        public string updated_by { get; set; }
        public string updated_datetime { get; set; }
        public string deleted_by { get; set; }
        public string deleted_datetime { get; set; }
    
        public virtual sir_access sir_access { get; set; }
        public virtual sir_category sir_category { get; set; }
    }
}
