//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sir_staff_item
    {
        public string sir_staff_item_id { get; set; }
        public string staff_id { get; set; }
        public string sir_item_id { get; set; }
        public string sir_staff_item_description { get; set; }
        public string sir_staff_item_file_attached { get; set; }
        public string sir_staff_item_file_old_name { get; set; }
        public string sir_staff_item_file_new_name { get; set; }
        public string sir_staff_item_complete { get; set; }
        public string sir_staff_item_status { get; set; }
        public string created_by { get; set; }
        public string created_datetime { get; set; }
        public string updated_by { get; set; }
        public string updated_datetime { get; set; }
        public string deleted_by { get; set; }
        public string deleted_datetime { get; set; }
    
        public virtual sir_item sir_item { get; set; }
    }
}
