//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sir_access
    {
        public sir_access()
        {
            this.sir_category_access = new HashSet<sir_category_access>();
        }
    
        public string sir_access_id { get; set; }
        public string staff_id { get; set; }
        public string sir_access_manage_user { get; set; }
        public string sir_access_is_admin { get; set; }
        public string sir_access_status { get; set; }
        public string created_by { get; set; }
        public string created_datetime { get; set; }
        public string updated_by { get; set; }
        public string updated_datetime { get; set; }
        public string deleted_by { get; set; }
        public string deleted_datetime { get; set; }
    
        public virtual ICollection<sir_category_access> sir_category_access { get; set; }
    }
}
