//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_login_history
    {
        public string staff_login_history_id { get; set; }
        public string staff_id { get; set; }
        public System.DateTime staff_login_history_datetime { get; set; }
    }
}
