//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stafftest
    {
        public int staffid { get; set; }
        public string staff_id { get; set; }
        public Nullable<int> country_office_id { get; set; }
        public Nullable<int> sub_office_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> contract_type_id { get; set; }
        public Nullable<int> functional_title_id { get; set; }
        public string staff_login { get; set; }
        public string staff_first_name { get; set; }
        public string staff_last_name { get; set; }
        public string staff_created_by { get; set; }
        public string staff_created_datetime { get; set; }
        public string staff_status { get; set; }
        public string staff_index_number { get; set; }
        public string staff_vendor_number { get; set; }
        public string staff_nationality { get; set; }
        public string staff_address { get; set; }
        public Nullable<System.DateTime> staff_dob { get; set; }
        public Nullable<System.DateTime> staff_eod { get; set; }
        public Nullable<System.DateTime> staff_nte { get; set; }
        public string staff_extension_number { get; set; }
        public string staff_email { get; set; }
        public string staff_access_main { get; set; }
        public string staff_access_dts { get; set; }
        public string staff_access_tb { get; set; }
        public string staff_access_ct { get; set; }
        public string staff_access_li { get; set; }
        public string staff_access_lc { get; set; }
        public string staff_access_sr { get; set; }
        public string staff_access_admin { get; set; }
        public string staff_last_updated_by { get; set; }
        public string staff_last_updated_datetime { get; set; }
        public string staff_deleted_by { get; set; }
        public string staff_deleted_datetime { get; set; }
        public Nullable<int> staff_supervisorid { get; set; }
        public Nullable<int> stuff_contract_details { get; set; }
        public Nullable<int> staff_warden { get; set; }
        public Nullable<int> alternate_warden_1 { get; set; }
        public Nullable<int> alternate_warden_2 { get; set; }
        public string Call_Sign { get; set; }
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> governorates_code { get; set; }
        public Nullable<int> areacode { get; set; }
        public Nullable<bool> cate { get; set; }
        public string international { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> WardenZone { get; set; }
        public Nullable<int> WardenGroupId { get; set; }
    }
}
