//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.dependents = new HashSet<dependent>();
            this.Evaluations = new HashSet<Evaluation>();
            this.staff1 = new HashSet<staff>();
            this.contract_details1 = new HashSet<contract_details>();
            this.contract_type1 = new HashSet<contract_type>();
            this.functional_title1 = new HashSet<functional_title>();
            this.staff11 = new HashSet<staff>();
            this.staff12 = new HashSet<staff>();
            this.staff13 = new HashSet<staff>();
            this.CourseRegs = new HashSet<CourseReg>();
            this.MissionAuthorizations = new HashSet<MissionAuthorization>();
            this.requests = new HashSet<request>();
            this.requests1 = new HashSet<request>();
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
            this.VAC_TRANS = new HashSet<VAC_TRANS>();
            this.TRAINING_CERTIFICATION = new HashSet<TRAINING_CERTIFICATION>();
            this.MissionAuthorization1 = new HashSet<MissionAuthorization1>();
            this.Attends = new HashSet<Attend>();
            this.Staff_Event = new HashSet<Staff_Event>();
            this.MissionAuthorizations1 = new HashSet<MissionAuthorization>();
        }
    
        public int staffid { get; set; }
        public string staff_id { get; set; }
        public Nullable<int> country_office_id { get; set; }
        public Nullable<int> sub_office_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> contract_type_id { get; set; }
        public Nullable<int> functional_title_id { get; set; }
        public string staff_login { get; set; }
        public string staff_first_name { get; set; }
        public string staff_last_name { get; set; }
        public string staff_created_by { get; set; }
        public string staff_created_datetime { get; set; }
        public string staff_status { get; set; }
        public string staff_index_number { get; set; }
        public string staff_vendor_number { get; set; }
        public string staff_nationality { get; set; }
        public string staff_address { get; set; }
        public Nullable<System.DateTime> staff_dob { get; set; }
        public Nullable<System.DateTime> staff_eod { get; set; }
        public Nullable<System.DateTime> staff_nte { get; set; }
        public string staff_extension_number { get; set; }
        public string staff_email { get; set; }
        public string staff_access_main { get; set; }
        public string staff_access_dts { get; set; }
        public string staff_access_tb { get; set; }
        public string staff_access_ct { get; set; }
        public string staff_access_li { get; set; }
        public string staff_access_lc { get; set; }
        public string staff_access_sr { get; set; }
        public string staff_access_admin { get; set; }
        public string staff_last_updated_by { get; set; }
        public string staff_last_updated_datetime { get; set; }
        public string staff_deleted_by { get; set; }
        public string staff_deleted_datetime { get; set; }
        public Nullable<int> staff_supervisorid { get; set; }
        public Nullable<int> stuff_contract_details { get; set; }
        public Nullable<int> staff_warden { get; set; }
        public Nullable<int> alternate_warden_1 { get; set; }
        public Nullable<int> alternate_warden_2 { get; set; }
        public string Call_Sign { get; set; }
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> governorates_code { get; set; }
        public Nullable<int> areacode { get; set; }
        public string international { get; set; }
        public Nullable<bool> cate { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> WardenZone { get; set; }
        public Nullable<int> WardenGroupId { get; set; }
    
        public virtual contract_details contract_details { get; set; }
        public virtual contract_type contract_type { get; set; }
        public virtual Country_office Country_office { get; set; }
        public virtual ICollection<dependent> dependents { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual functional_title functional_title { get; set; }
        public virtual ICollection<staff> staff1 { get; set; }
        public virtual staff staff2 { get; set; }
        public virtual sub_office sub_office { get; set; }
        public virtual unit unit { get; set; }
        public virtual ICollection<contract_details> contract_details1 { get; set; }
        public virtual ICollection<contract_type> contract_type1 { get; set; }
        public virtual country country { get; set; }
        public virtual ICollection<functional_title> functional_title1 { get; set; }
        public virtual ICollection<staff> staff11 { get; set; }
        public virtual staff staff3 { get; set; }
        public virtual ICollection<staff> staff12 { get; set; }
        public virtual staff staff4 { get; set; }
        public virtual ICollection<staff> staff13 { get; set; }
        public virtual staff staff5 { get; set; }
        public virtual governorate governorate { get; set; }
        public virtual district district { get; set; }
        public virtual category category { get; set; }
        public virtual district district1 { get; set; }
        public virtual WardenGroup WardenGroup { get; set; }
        public virtual ICollection<CourseReg> CourseRegs { get; set; }
        public virtual ICollection<MissionAuthorization> MissionAuthorizations { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<request> requests1 { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual ICollection<VAC_TRANS> VAC_TRANS { get; set; }
        public virtual ICollection<TRAINING_CERTIFICATION> TRAINING_CERTIFICATION { get; set; }
        public virtual ICollection<MissionAuthorization1> MissionAuthorization1 { get; set; }
        public virtual ICollection<Attend> Attends { get; set; }
        public virtual ICollection<Staff_Event> Staff_Event { get; set; }
        public virtual ICollection<MissionAuthorization> MissionAuthorizations1 { get; set; }
    }
}
