//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_pwd
    {
        public string staff_pwd_id { get; set; }
        public string staff_id { get; set; }
        public byte[] staff_pwd_pwd { get; set; }
        public string staff_pwd_created_by { get; set; }
        public System.DateTime staff_pwd_created_datetime { get; set; }
        public string staff_pwd_status { get; set; }
        public string staff_pwd_is_expired { get; set; }
        public string staff_pwd_need_change { get; set; }
    }
}
