//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_office
    {
        public sub_office()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int subofficeid { get; set; }
        public string sub_office_id { get; set; }
        public string office_description_english { get; set; }
        public string office_abreviation_english { get; set; }
        public string office_description_french { get; set; }
        public string office_abreviation_french { get; set; }
        public string office_status { get; set; }
        public string office_created_by { get; set; }
        public Nullable<System.DateTime> office_created_datetime { get; set; }
        public string office_last_modified_by { get; set; }
        public Nullable<System.DateTime> office_last_modified_datetime { get; set; }
        public string office_deleted_by { get; set; }
        public Nullable<System.DateTime> office_deleted_datetime { get; set; }
        public Nullable<int> countryofficeid { get; set; }
    
        public virtual Country_office Country_office { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
    }
}
