//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALARM_OUTPUT_WAVE
    {
        public int nOutputWaveIdn { get; set; }
        public string sName { get; set; }
        public int nDelay { get; set; }
        public int nCount { get; set; }
        public int nHigh { get; set; }
        public int nLow { get; set; }
    }
}
