//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALARM_EMAIL
    {
        public int nAlarmEmailIdn { get; set; }
        public int nEmailIdn1 { get; set; }
        public int nEmailIdn2 { get; set; }
        public int nEmailIdn3 { get; set; }
        public int nEmailIdn4 { get; set; }
        public int nEmailIdn5 { get; set; }
    }
}
