//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ACCESSGROUP_DOOR
    {
        public int nAccessDoorIdn { get; set; }
        public int nAccessIdn { get; set; }
        public int nType { get; set; }
        public int nAgentIdn { get; set; }
        public int nTimezone { get; set; }
    }
}
