//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALARM
    {
        public int nAlarmIdn { get; set; }
        public int nSWAlarmIdn { get; set; }
        public int nOutputDeviceSoundIdn { get; set; }
        public int nOutputReaderIdn { get; set; }
        public int nOutputPort { get; set; }
        public int nOutputWaveIdn { get; set; }
        public int nAlarmEmailIdn { get; set; }
        public string sDescription { get; set; }
    }
}
