//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARD_MIFARE_LAYOUT
    {
        public int nMifareIdn { get; set; }
        public int nCISIdn { get; set; }
        public int nNumOfTemplate { get; set; }
        public int nTemplateSize { get; set; }
        public int nTemplateBlock1 { get; set; }
        public int nTemplateBlock2 { get; set; }
        public int nTemplateBlock3 { get; set; }
        public int nTemplateBlock4 { get; set; }
    }
}
