//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARD
    {
        public int nCardIdn { get; set; }
        public short nIndex { get; set; }
        public short nType { get; set; }
        public string sCardNo { get; set; }
        public int nUserIdn { get; set; }
        public int nSecurityLevel { get; set; }
        public int nAccessgroup { get; set; }
    }
}
