//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DOOR_READER
    {
        public int nDoorIdn { get; set; }
        public int nReaderIdn { get; set; }
        public short nInout { get; set; }
        public int nOpenRelay { get; set; }
        public int nOpenTime { get; set; }
        public int nCloseTime { get; set; }
        public int nOpenEvent { get; set; }
        public int nRTE { get; set; }
        public int nRTEType { get; set; }
        public int nSensor { get; set; }
        public int nSensorType { get; set; }
        public int nCloseEvent { get; set; }
    }
}
