//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EVENT_FACE
    {
        public int nEventFaceIdn { get; set; }
        public int nEventLogIdn { get; set; }
        public short nType { get; set; }
        public byte[] bFaceImage { get; set; }
        public int nFaceImageLen { get; set; }
    }
}
