//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HOLIDAY_DATE
    {
        public int nHoliday { get; set; }
        public int nDate { get; set; }
        public short nYearRepeat { get; set; }
        public int nDaysLong { get; set; }
    }
}
