//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LEAVE
    {
        public int nLeaveIdn { get; set; }
        public string sName { get; set; }
        public int nType { get; set; }
        public int nStartTime { get; set; }
        public int nEndTime { get; set; }
        public string sDescription { get; set; }
    }
}
