//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OPERATOR_EMAIL
    {
        public int nEmailIdn { get; set; }
        public string sSMTPServer { get; set; }
        public string sUserID { get; set; }
        public string sPassword { get; set; }
        public string sSender { get; set; }
        public string sRecipient { get; set; }
    }
}
