//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_DISPLAY
    {
        public int nReaderIdn { get; set; }
        public int nLanguage { get; set; }
        public int nBackground { get; set; }
        public int nSubInfo { get; set; }
        public int nMenuTimeout { get; set; }
        public int nMessageTimeout { get; set; }
        public short nPrivateAuth { get; set; }
        public int nVolume { get; set; }
        public short nDateType { get; set; }
        public short nTimeSync { get; set; }
    }
}
