//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_INPUT
    {
        public int nReaderIOIdn { get; set; }
        public int nReaderIdn { get; set; }
        public int nInputType { get; set; }
        public int nFunctionType { get; set; }
        public int nDurationTime { get; set; }
        public int nSwitchType { get; set; }
        public int nTimezone { get; set; }
    }
}
