//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_OUTPUT
    {
        public int nReaderIOIdn { get; set; }
        public int nReaderIdn { get; set; }
        public int nEvent { get; set; }
        public int nDeviceID { get; set; }
        public short nRelayPort { get; set; }
        public short nRelayOn { get; set; }
        public int nOutputWaveIdn { get; set; }
        public int nPriority { get; set; }
    }
}
