//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_WLAN
    {
        public int nReaderIdn { get; set; }
        public short nPresetIndex { get; set; }
        public string sName { get; set; }
        public int nOperationMode { get; set; }
        public string sEssid { get; set; }
        public int nAuthType { get; set; }
        public int nEncryption { get; set; }
        public int nKeyType { get; set; }
        public string sKey { get; set; }
    }
}
