//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_HW
    {
        public int nReaderIdn { get; set; }
        public string sProductName { get; set; }
        public string sBoardVersion { get; set; }
        public string sFirmwareVersion { get; set; }
        public string sBlackfinVersion { get; set; }
        public string sKernelVersion { get; set; }
        public string sPrivateKey { get; set; }
    }
}
