//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_FINGER
    {
        public int nReaderIdn { get; set; }
        public int nSecurity { get; set; }
        public int nFastMode { get; set; }
        public int nImageQuality { get; set; }
        public short nViewImage { get; set; }
        public int nTimeout { get; set; }
        public int nFreeScanDelay { get; set; }
        public int nMatchTimeout { get; set; }
        public short nCheckDuplicate { get; set; }
        public short nEncryption { get; set; }
    }
}
