//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER_DEPT
    {
        public int nDeptIdn { get; set; }
        public int nDeptType { get; set; }
        public string sName { get; set; }
        public int nDepth { get; set; }
        public int nParentIdn { get; set; }
        public int nParentReaderIdn { get; set; }
        public string sDescription { get; set; }
    }
}
