//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SITEGRAPHICS_OBJECTINFO
    {
        public int nSiteGraphicsIdn { get; set; }
        public byte[] bDoorsObject { get; set; }
        public int nDoorsObjectLen { get; set; }
    }
}
