//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SECUREIO
    {
        public int nSecureIOIdn { get; set; }
        public int nReaderIdn { get; set; }
        public int nIndex { get; set; }
        public short nInput0 { get; set; }
        public short nInput1 { get; set; }
        public short nInput2 { get; set; }
        public short nInput3 { get; set; }
        public short nOutput0 { get; set; }
        public short nOutput1 { get; set; }
    }
}
