//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TA_TIMESLOT
    {
        public int nTimeSlotIdn { get; set; }
        public int nDailyScheduleIdn { get; set; }
        public int nStartTime { get; set; }
        public int nEndTime { get; set; }
        public int nTimeCategoryIdn { get; set; }
        public int nStartGrace { get; set; }
        public int nEndGrace { get; set; }
        public int nInRounding { get; set; }
        public int nOutRounding { get; set; }
        public int nMinimumDuration { get; set; }
        public short nMustCheckIn { get; set; }
        public short nMustCheckOut { get; set; }
        public short nAutoCheckIn { get; set; }
        public short nAutoCheckOut { get; set; }
        public short nAffectingResult { get; set; }
    }
}
