//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIMEZONE_DAY
    {
        public int nTimezone { get; set; }
        public int nDay { get; set; }
        public int nHolidayIdn { get; set; }
        public int nTimecode { get; set; }
    }
}
