//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TA_DEVICE_EVENT_KEY
    {
        public int nDeviceEventKeyIdn { get; set; }
        public int nReaderIdn { get; set; }
        public int nKeyIdn { get; set; }
        public int nKeyEvent { get; set; }
        public short nNoLate { get; set; }
        public short nIsOnlyResult { get; set; }
        public short nIsWorkTime { get; set; }
        public string sEventName { get; set; }
    }
}
