//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRACE_USER
    {
        public int nLogIdn { get; set; }
        public int nDateTime { get; set; }
        public string sAdminID { get; set; }
        public string sAdminIP { get; set; }
        public string sAccessType { get; set; }
        public string sUserName { get; set; }
        public string sDepartment { get; set; }
        public string sTelNumber { get; set; }
        public string sEmail { get; set; }
        public string sUserID { get; set; }
        public string sPassword { get; set; }
        public int nStartDate { get; set; }
        public int nEndDate { get; set; }
        public int nAdminLevel { get; set; }
    }
}
