//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TA_HOLIDAY_RULE_DATA
    {
        public int nHolidayRuleDataIdn { get; set; }
        public int nHolidayRuleIdn { get; set; }
        public int nHolidayIdn { get; set; }
    }
}
