//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TA_TIMECATEGORY
    {
        public int nTimeCategoryIdn { get; set; }
        public string sName { get; set; }
        public float nTimeRate { get; set; }
        public int nRoundingUnit { get; set; }
        public short nRoundingType { get; set; }
        public int nDisplayColor { get; set; }
        public string sDescription { get; set; }
    }
}
