//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_EX
    {
        public int nUserIdn { get; set; }
        public string sSurName { get; set; }
        public string sFirstName { get; set; }
        public string sMiddleName { get; set; }
        public int nImageSize { get; set; }
        public string sImageFilePath { get; set; }
        public int nDuration { get; set; }
        public int nCountPerDay { get; set; }
        public short nUsePrivateImage { get; set; }
        public string sGreetingMsg { get; set; }
    }
}
