//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_CUSTOMFIELD
    {
        public int nFieldIdn { get; set; }
        public string sFieldName { get; set; }
        public int nFieldType { get; set; }
        public int nDataType { get; set; }
        public short nEssential { get; set; }
        public int nValueIdn { get; set; }
        public string sData { get; set; }
    }
}
