//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ZONE_INPUT
    {
        public int nZoneIdn { get; set; }
        public int nReaderIOIdn { get; set; }
        public string sName { get; set; }
        public int nInputFlag { get; set; }
    }
}
