//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ZONE_CONTROL
    {
        public int nZoneIdn { get; set; }
        public int nUserIdn { get; set; }
        public int nNumOfEntrance { get; set; }
        public short nFlag { get; set; }
        public int nTime { get; set; }
    }
}
