//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ZONE_ALARMZONE
    {
        public int nZoneIdn { get; set; }
        public int nType { get; set; }
        public int nLockDelayTime { get; set; }
        public int nUnlockDelayTime { get; set; }
        public int nStatus { get; set; }
        public short nSoundStatus { get; set; }
        public int nArmKey { get; set; }
        public int nArmCardID { get; set; }
        public int nArmCustomID { get; set; }
        public int nDisarmKey { get; set; }
        public int nDisarmCardID { get; set; }
        public int nDisarmCustomID { get; set; }
    }
}
