//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ZONE_ELZONE
    {
        public int nZoneIdn { get; set; }
        public int nLimitTime { get; set; }
        public int nTimezone { get; set; }
        public int nStartTime1 { get; set; }
        public int nEndTime1 { get; set; }
        public int nLimitNumber1 { get; set; }
        public int nStartTime2 { get; set; }
        public int nEndTime2 { get; set; }
        public int nLimitNumber2 { get; set; }
        public int nStartTime3 { get; set; }
        public int nEndTime3 { get; set; }
        public int nLimitNumber3 { get; set; }
        public int nStartTime4 { get; set; }
        public int nEndTime4 { get; set; }
        public int nLimitNumber4 { get; set; }
    }
}
