//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_Attends
    {
        public int Attend_ID { get; set; }
        public string Trainer_ID { get; set; }
        public string Plan_ID { get; set; }
        public string Traines_ID { get; set; }
        public string TRAINING_SC_id { get; set; }
        public Nullable<bool> Attend { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Deascription { get; set; }
        public string sc_id { get; set; }
    
        public virtual TRAINING_SC TRAINING_SC { get; set; }
    }
}
