//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_COMPANIES
    {
        public TRAINING_COMPANIES()
        {
            this.TRAINING_PLAN_TRAINING_COMPANIES = new HashSet<TRAINING_PLAN_TRAINING_COMPANIES>();
            this.TRAINING_TRAINING_COMPANIES = new HashSet<TRAINING_TRAINING_COMPANIES>();
        }
    
        public string TRAINING_COMPANY_ID { get; set; }
        public string TRAINING_COMPANY_NAME { get; set; }
        public string ADRESS { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
    
        public virtual ICollection<TRAINING_PLAN_TRAINING_COMPANIES> TRAINING_PLAN_TRAINING_COMPANIES { get; set; }
        public virtual ICollection<TRAINING_TRAINING_COMPANIES> TRAINING_TRAINING_COMPANIES { get; set; }
    }
}
