//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PLAN_TRAININGS
    {
        public string PLAN_ID { get; set; }
        public string TRAINING_ID { get; set; }
        public Nullable<bool> REQUIRE_CERTIFICATE { get; set; }
        public string CERTIFICATE_ID { get; set; }
        public string COASTPEREMP { get; set; }
        public string EMPLPERCENTAGE { get; set; }
        public string FAILPASSDEPENDANCY { get; set; }
        public string IFFAILPERCENTAGE { get; set; }
        public string IFPASSPERCENTAGE { get; set; }
        public string TRAINING_TYPE { get; set; }
    
        public virtual TRAINING_PLAN TRAINING_PLAN { get; set; }
        public virtual TRAINING_TYPE TRAINING_TYPE1 { get; set; }
    }
}
