//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_SC
    {
        public string sc_id { get; set; }
        public Nullable<System.DateTime> from_time { get; set; }
        public Nullable<System.DateTime> to_time { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string attend { get; set; }
        public string PLAN_ID { get; set; }
        public Nullable<System.DateTime> time_open { get; set; }
        public string extra1 { get; set; }
        public Nullable<int> extra2 { get; set; }
        public string extra3 { get; set; }
        public Nullable<System.DateTime> time_closed { get; set; }
        public string comment { get; set; }
    
        public virtual TRAINING_PLAN TRAINING_PLAN { get; set; }
    }
}
