//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_CERTIFICATION
    {
        public int certID { get; set; }
        public string certName { get; set; }
        public string cert_course_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string TRAINING_ID { get; set; }
        public Nullable<int> CERT1 { get; set; }
        public string CERT2 { get; set; }
        public string COMMENT { get; set; }
        public string CERT3 { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual TRAINING TRAINING { get; set; }
    }
}
