//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PLAN_TRAINING_CLASSES
    {
        public TRAINING_PLAN_TRAINING_CLASSES()
        {
            this.TRAINEES = new HashSet<TRAINEE>();
        }
    
        public string PLAN_ID { get; set; }
        public string TRAINING_ID { get; set; }
        public string CLASS_ID { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<System.DateTime> FROM_TIME { get; set; }
        public Nullable<System.DateTime> TO_TIME { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
    
        public virtual ICollection<TRAINEE> TRAINEES { get; set; }
        public virtual TRAINING_PLAN TRAINING_PLAN { get; set; }
    }
}
