//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINER
    {
        public TRAINER()
        {
            this.TRAINING_PLAN_TRAINERS = new HashSet<TRAINING_PLAN_TRAINERS>();
        }
    
        public string TRAINING_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public string non1 { get; set; }
        public Nullable<int> non2 { get; set; }
        public string non3 { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual TRAINING TRAINING { get; set; }
        public virtual ICollection<TRAINING_PLAN_TRAINERS> TRAINING_PLAN_TRAINERS { get; set; }
    }
}
