//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PLAN
    {
        public TRAINING_PLAN()
        {
            this.TRAINING_PLAN_TRAINING_CLASSES = new HashSet<TRAINING_PLAN_TRAINING_CLASSES>();
            this.TRAINING_PLAN_TRAININGS = new HashSet<TRAINING_PLAN_TRAININGS>();
            this.TRAINING_SC = new HashSet<TRAINING_SC>();
        }
    
        public string PLAN_ID { get; set; }
        public string TRAINING_PLACE { get; set; }
        public Nullable<System.DateTime> PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> PERIOD_TO { get; set; }
    
        public virtual ICollection<TRAINING_PLAN_TRAINING_CLASSES> TRAINING_PLAN_TRAINING_CLASSES { get; set; }
        public virtual ICollection<TRAINING_PLAN_TRAININGS> TRAINING_PLAN_TRAININGS { get; set; }
        public virtual ICollection<TRAINING_SC> TRAINING_SC { get; set; }
    }
}
