//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TYPE
    {
        public TRAINING_TYPE()
        {
            this.TRAINING_PLAN_TRAININGS = new HashSet<TRAINING_PLAN_TRAININGS>();
        }
    
        public string type_id { get; set; }
        public string type_name { get; set; }
        public string comment { get; set; }
        public string typ01 { get; set; }
        public Nullable<int> type02 { get; set; }
        public string type22 { get; set; }
    
        public virtual ICollection<TRAINING_PLAN_TRAININGS> TRAINING_PLAN_TRAININGS { get; set; }
    }
}
