//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINEE
    {
        public string PLAN_ID { get; set; }
        public string TRAINING_ID { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<bool> ATTENDED { get; set; }
        public Nullable<bool> PASSED { get; set; }
        public string TRAINING_EVALUATION { get; set; }
        public string TRAINER_EVALUATION { get; set; }
        public string CLASS_ID { get; set; }
    
        public virtual TRAINING_PLAN_TRAINING_CLASSES TRAINING_PLAN_TRAINING_CLASSES { get; set; }
        public virtual TRAINING TRAINING { get; set; }
    }
}
