//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        public unit()
        {
            this.staffs = new HashSet<staff>();
            this.requests = new HashSet<request>();
            this.Courses = new HashSet<Cours>();
        }
    
        public int unitid { get; set; }
        public string unit_id { get; set; }
        public string unit_description_english { get; set; }
        public string unit_abreviation_english { get; set; }
        public string unit_description_french { get; set; }
        public string unit_abreviation_french { get; set; }
        public string unit_status { get; set; }
        public string unit_created_by { get; set; }
        public Nullable<System.DateTime> unit_created_datetime { get; set; }
        public string unit_last_modified_by { get; set; }
        public Nullable<System.DateTime> unit_last_modified_datetime { get; set; }
        public string unit_deleted_by { get; set; }
        public Nullable<System.DateTime> unit_deleted_datetime { get; set; }
        public string unit_short_abreviation { get; set; }
        public Nullable<int> office_id { get; set; }
        public Nullable<int> HOU_ID { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
        public virtual Country_office Country_office { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
