//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAC_HISTORY_PRD
    {
        public string PRDID { get; set; }
        public string EMP_ID { get; set; }
        public string GRPID { get; set; }
        public string ORGPRDID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
    }
}
