//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAC_HISTORY
    {
        public string PRDID { get; set; }
        public string VACPERIODID { get; set; }
        public string ORGVACTYPEID { get; set; }
        public Nullable<bool> USERATIO { get; set; }
        public Nullable<double> VACDAYS { get; set; }
        public Nullable<double> VACTAKEN { get; set; }
        public Nullable<double> VACACC { get; set; }
        public Nullable<double> VACOB { get; set; }
    }
}
