//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAC_TRANS
    {
        public string TRANS_ID { get; set; }
        public string EMP_ID { get; set; }
        public string VACATION_TYPE_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<double> DAY_COUNT { get; set; }
        public string REASON { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> FROMTIME { get; set; }
        public Nullable<System.DateTime> TOTIME { get; set; }
        public string VACPHONE { get; set; }
        public string VACADDRESS { get; set; }
        public Nullable<int> DAYTYPENO { get; set; }
        public Nullable<int> SECOND_DAY { get; set; }
        public Nullable<System.DateTime> ASSFDATE { get; set; }
        public Nullable<System.DateTime> ASSTDATE { get; set; }
        public Nullable<bool> IN_WEEKEND { get; set; }
        public Nullable<bool> IN_HOLIDAY { get; set; }
        public Nullable<int> empid { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual VACATION_TYPE_LIST VACATION_TYPE_LIST { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
