//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACATION_PERIODS
    {
        public string VACATION_PERIOD_ID { get; set; }
        public string VACATION_GROUP_ID { get; set; }
        public Nullable<System.DateTime> V_START { get; set; }
        public Nullable<System.DateTime> V_END { get; set; }
    }
}
