//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACATION_GROUP_DETAILS
    {
        public string VACATION_PERIOD_ID { get; set; }
        public string VACATION_TYPE_ID { get; set; }
        public string VACATION_DET_ID { get; set; }
        public Nullable<double> ALLOWED_COUNT { get; set; }
        public bool ALLOW_ACCUMULATION { get; set; }
        public bool CONSIDER_WEEKEND_AS_VAC { get; set; }
        public bool CONSIDER_HOLIDAY_AS_VAC { get; set; }
        public bool EDGED_WEEKEND_AS_VAC { get; set; }
        public bool EDGED_HOLIDAY_AS_VAC { get; set; }
        public bool EDGED_WEEKEND_AS_VAC_END { get; set; }
        public bool EDGED_HOLIDAY_AS_VAC_END { get; set; }
        public Nullable<bool> ISALLOWED { get; set; }
        public string VAC_TYPE_ACC { get; set; }
        public Nullable<double> MAX_ACC { get; set; }
    }
}
