//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACATION_TYPE_LIST
    {
        public VACATION_TYPE_LIST()
        {
            this.VAC_TRANS = new HashSet<VAC_TRANS>();
        }
    
        public string VACATION_TYPE_ID { get; set; }
        public string VACATION_TYPE_NAME { get; set; }
    
        public virtual ICollection<VAC_TRANS> VAC_TRANS { get; set; }
    }
}
