//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int ID { get; set; }
        public string VendorID { get; set; }
        public string VendorName { get; set; }
        public string non1 { get; set; }
        public Nullable<int> non2 { get; set; }
        public Nullable<System.DateTime> non3 { get; set; }
    }
}
