//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LogData
    {
        public string sLogTime { get; set; }
        public string sName { get; set; }
        public int nEventIdn { get; set; }
        public int nUserID { get; set; }
    }
}
